name: UltimateBingo
version: '${project.version}'
main: io.shantek.UltimateBingo
api-version: '1.20'

# 将 PlaceholderAPI 与 WorldGuard 设置为插件的可选依赖。
softdepend: [PlaceholderAPI, WorldGuard]

commands:
  bingo:
    description: 打开当前宾果卡片；添加 start 或 stop 来开始或结束游戏；使用 settings 配置设置

permissions:
  shantek.ultimatebingo.start:
    description: 允许玩家使用 start 命令开始游戏
    default: op

  shantek.ultimatebingo.stop:
    description: 允许玩家使用 stop 命令停止游戏
    default: op

  shantek.ultimatebingo.settings:
    description: 允许玩家在游戏中添加/移除物品
    default: op

  shantek.ultimatebingo.signs:
    description: 允许玩家使用游戏内告示牌配置并开始游戏
    default: op
